trigger:
  branches:
    include: [ main ]

stages:
- stage: CI
  displayName: "CI"
  jobs:

  # ---------- FRONTEND ----------
  - job: Front
    displayName: "Build & Test Frontend"
    pool: { name: MiPool }  
    steps:
      - checkout: self

      - task: NodeTool@0
        displayName: "Use Node 20.x"  
        inputs:
          versionSpec: '20.x'

      - task: CmdLine@2
        displayName: "npm ci"
        inputs:
          script: npm ci
          workingDirectory: '$(Build.SourcesDirectory)/frontend/gameTracker'

      - task: CmdLine@2
        displayName: "Run Vitest (coverage)"
        inputs:
          script: npm run coverage
          workingDirectory: '$(Build.SourcesDirectory)/frontend/gameTracker'

      - task: PublishTestResults@2
        displayName: "Publish frontend JUnit"
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test-results-*.xml'
          searchFolder: '$(Build.SourcesDirectory)/frontend/gameTracker'
          testRunTitle: 'Frontend - Vitest'
          mergeTestResults: true
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: "Publish frontend coverage artifact"
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/frontend/gameTracker/coverage'
          ArtifactName: 'front_coverage'
        condition: always()

      - task: CmdLine@2
        displayName: "npm run build"
        inputs:
          script: npm run build
          workingDirectory: '$(Build.SourcesDirectory)/frontend/gameTracker'

      - task: PublishBuildArtifacts@1
        displayName: "Publish front (dist)"
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/frontend/gameTracker/dist'
          ArtifactName: 'front_dist'

  # ---------- BACKEND ----------
  - job: Back
    displayName: "Build & Test Backend (Go → Linux)"
    pool: { name: MiPool }  
    steps:
      - checkout: self

      - task: GoTool@0
        displayName: "Use Go 1.22.x"
        inputs:
          version: '1.22'

      - task: PowerShell@2
        displayName: "go tidy + install test tooling + run tests (gotestsum)"
        inputs:
          targetType: 'inline'
          script: |
            cd "$(Build.SourcesDirectory)\backend"
            go mod tidy

            $gopath = (& go env GOPATH)
            if (-not $gopath) { throw "GOPATH no definido" }
            $bin = Join-Path $gopath "bin"
            $env:PATH = "$bin;$env:PATH"

            go install gotest.tools/gotestsum@latest
            go install github.com/boumenot/gocover-cobertura@latest

            gotestsum --format=standard-verbose --junitfile "test-results-go.xml" -- -covermode=atomic -coverprofile="coverage.out" ./service ./controller ./models

            gocover-cobertura < coverage.out > coverage.xml

      - task: PublishTestResults@2
        displayName: "Publish backend JUnit"
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'backend/test-results-go.xml'
          testRunTitle: 'Backend - go tests'
        condition: always()

      - task: PublishCodeCoverageResults@2
        displayName: "Publish backend coverage (Cobertura)"
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: 'backend/coverage.xml'
          pathToSources: 'backend'
        condition: always()

      - task: PowerShell@2
        displayName: "go build (GOOS=linux GOARCH=amd64 CGO=0)"
        inputs:
          targetType: 'inline'
          script: |
            cd "$(Build.SourcesDirectory)\backend"
            mkdir -Force bin | Out-Null
            $env:GOOS="linux"
            $env:GOARCH="amd64"
            $env:CGO_ENABLED="0"
            go build -o bin/server -ldflags="-s -w" .

      - task: PowerShell@2
        displayName: "Copy startup.sh → bin/"
        inputs:
          targetType: 'inline'
          script: |
            cd "$(Build.SourcesDirectory)\backend"
            Copy-Item -Path ".\startup.sh" -Destination ".\bin\startup.sh" -Force

      - task: PublishBuildArtifacts@1
        displayName: "Publish back (bin)"
        inputs:
          PathtoPublish: 'backend/bin'
          ArtifactName: 'back_bin'